export const CartTypes = {
  ADD_ITEM_CART: 'ADD_ITEM_CART',

  INCREMENT_ITEM_CART: 'INCREMENT_ITEM_CART',
  DECREMENT_ITEM_CART: 'DECREMENT_ITEM_CART',

  CHANGER_VISIBLE_MODAL_CART: 'CHANGER_VISIBLE_MODAL_CART',

  CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
}
